/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanadamal
 */
public class issure_books extends javax.swing.JFrame {

    /**
     * Creates new form issure_books
     */
    int x,y;
    public issure_books() {
        initComponents();
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lable_one = new javax.swing.JLabel();
        lable_three = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b_id = new javax.swing.JTextField();
        s_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lable_one.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        lable_one.setText("Back");
        lable_one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lable_oneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lable_oneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lable_oneMouseExited(evt);
            }
        });
        jPanel1.add(lable_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        lable_three.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        lable_three.setForeground(new java.awt.Color(255, 255, 255));
        lable_three.setText("Cancel");
        lable_three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lable_threeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lable_threeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lable_threeMouseExited(evt);
            }
        });
        jPanel1.add(lable_three, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book ID      :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 135, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 198, 110, -1));

        b_id.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jPanel1.add(b_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 132, 277, -1));

        s_id.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jPanel1.add(s_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 195, 277, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Duration     : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 258, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<not selected>", "One Week", "Two Week" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 255, 277, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Issure Books");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 879, -1));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton1.setText("Issure");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 329, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib_system/minimize.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib_system/close.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 30, -1, 420));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib_system/issure_books_background.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 880, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lable_oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_oneMouseClicked
        // TODO add your handling code here:
        menu a= new menu();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_lable_oneMouseClicked

    private void lable_threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_threeMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Don't You Issure This Book !", "Question", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_NO_OPTION){
            b_id.setText("");
            s_id.setText("");
        }
    }//GEN-LAST:event_lable_threeMouseClicked

    private void lable_oneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_oneMouseEntered
        // TODO add your handling code here:
        lable_one.setForeground(Color.red);
    }//GEN-LAST:event_lable_oneMouseEntered

    private void lable_oneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_oneMouseExited
        // TODO add your handling code here:
        lable_one.setForeground(Color.black);
    }//GEN-LAST:event_lable_oneMouseExited

    private void lable_threeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_threeMouseEntered
        // TODO add your handling code here:
        lable_three.setForeground(Color.red);
    }//GEN-LAST:event_lable_threeMouseEntered

    private void lable_threeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_threeMouseExited
        // TODO add your handling code here:
        lable_three.setForeground(Color.white);
    }//GEN-LAST:event_lable_threeMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String duration = (String)jComboBox1.getSelectedItem();
        java.util.Date date = new java.util.Date();
        java.sql.Date sqldate = new java.sql.Date(date.getTime());
        if(b_id.getText().equals("") || duration.equals("<not selected>") || s_id.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Empty Feeld !!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                String sql_one ="select * from available_books where b_id=?";
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                PreparedStatement pstmt_one = conn.prepareStatement(sql_one);
                pstmt_one.setString(1, b_id.getText());
                ResultSet rs_one = pstmt_one.executeQuery();
                if(rs_one.next()){
                    
                    try{
                        String sql = "select * from issure_books where b_id=?";
                        PreparedStatement pstmt = conn.prepareStatement(sql);
                        pstmt.setString(1, b_id.getText());
                        ResultSet rs = pstmt.executeQuery();
                        if(rs.next()){
                            JOptionPane.showMessageDialog(this, "This Book is Already Issured !!", "Error", JOptionPane.ERROR_MESSAGE);
                        }else{
                            
                            try{
                            String sql_two ="select * from student_details where s_index=?";
                            PreparedStatement pstmt_two = conn.prepareStatement(sql_two);
                            pstmt_two.setString(1, s_id.getText());
                            ResultSet rs_two = pstmt_two.executeQuery();
                            if(rs_two.next()){

                                    try{
                                        String sql_six="select b_issure from all_books where b_id=?";
                                        PreparedStatement pstmt_six = conn.prepareStatement(sql_six);
                                        pstmt_six.setString(1, b_id.getText());
                                        ResultSet rs_six =pstmt_six.executeQuery();
                                        if(rs_six.next()){
                                            String issure =rs_six.getString(1);
                                            if(issure.equals("Yes")){
                                                try{
                                                    boolean result =false;
                                                    int value = 0;
                                                    String sql_three ="select s_id, count(s_id) from issure_books where s_id=? group by s_id";
                                                    PreparedStatement pstmt_three = conn.prepareStatement(sql_three);
                                                    pstmt_three.setString(1, s_id.getText());
                                                    ResultSet rs_three = pstmt_three.executeQuery();

                                                    if(rs_three.next() == false){
                                                        result = true;
                                                    }

                                                    if(rs_three.next()){
                                                        value =rs_three.getInt(2);
                                                    }

                                                    if(value >3){
                                                        JOptionPane.showMessageDialog(this, "We Issured Maximum Books Under this ID","Error",JOptionPane.ERROR_MESSAGE);
                                                    }else{
                                                        try{
                                                            String sql_four = "insert into issure_books values (?, ?, ?, ?)";
                                                            PreparedStatement pstmt_four = conn.prepareStatement(sql_four);
                                                            pstmt_four.setString(1, b_id.getText());
                                                            pstmt_four.setString(2, s_id.getText());
                                                            pstmt_four.setDate(3, sqldate);
                                                            pstmt_four.setString(4, duration);
                                                            pstmt_four.executeUpdate();

                                                            String sql_five = "delete from available_books where b_id=?";
                                                            PreparedStatement pstmt_five = conn.prepareStatement(sql_five);
                                                            pstmt_five.setString(1, b_id.getText());
                                                            pstmt_five.executeUpdate();

                                                            JOptionPane.showMessageDialog(this, "Successfuly Issured !! ");
                                                             b_id.setText("");
                                                             s_id.setText("");
                                                        }catch(Exception e){
                                                            JOptionPane.showMessageDialog(this, e);
                                                        }
                                                    }
                                                }catch(Exception e){
                                                    JOptionPane.showMessageDialog(this, e );
                                                }
                                            }else{
                                                JOptionPane.showMessageDialog(this, "Cannot Issure This Book");
                                            }
                                        }else{
                                            JOptionPane.showMessageDialog(this, "Cannot Identifier State");
                                        }
                                    }catch(Exception e){
                                        JOptionPane.showMessageDialog(this, e);
                                    }
                            }else{
                                JOptionPane.showMessageDialog(this, "Incorrect Student ID !!", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(this, e);
                        }
                            }
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(this, e);
                        }
                  /* try{
                        String sql_two ="select * from student_details where s_index=?";
                        PreparedStatement pstmt_two = conn.prepareStatement(sql_two);
                        pstmt_two.setString(1, s_id.getText());
                        ResultSet rs_two = pstmt_two.executeQuery();
                        if(rs_two.next()){
                                
                                try{
                                    String sql_six="select b_issure from all_books where b_id=?";
                                    PreparedStatement pstmt_six = conn.prepareStatement(sql_six);
                                    pstmt_six.setString(1, b_id.getText());
                                    ResultSet rs_six =pstmt_six.executeQuery();
                                    if(rs_six.next()){
                                        String issure =rs_six.getString(1);
                                        if(issure.equals("Yes")){
                                            try{
                                                boolean result =false;
                                                int value = 0;
                                                String sql_three ="select s_id, count(s_id) from issure_books where s_id=? group by s_id";
                                                PreparedStatement pstmt_three = conn.prepareStatement(sql_three);
                                                pstmt_three.setString(1, s_id.getText());
                                                ResultSet rs_three = pstmt_three.executeQuery();

                                                if(rs_three.next() == false){
                                                    result = true;
                                                }

                                                if(rs_three.next()){
                                                    value =rs_three.getInt(2);
                                                }

                                                if(value >3){
                                                    JOptionPane.showMessageDialog(this, "We Issured Maximum Books Under this ID","Error",JOptionPane.ERROR_MESSAGE);
                                                }else{
                                                    try{
                                                        String sql_four = "insert into issure_books values (?, ?, ?, ?)";
                                                        PreparedStatement pstmt_four = conn.prepareStatement(sql_four);
                                                        pstmt_four.setString(1, b_id.getText());
                                                        pstmt_four.setString(2, s_id.getText());
                                                        pstmt_four.setDate(3, sqldate);
                                                        pstmt_four.setString(4, duration);
                                                        pstmt_four.executeUpdate();

                                                        String sql_five = "delete from available_books where b_id=?";
                                                        PreparedStatement pstmt_five = conn.prepareStatement(sql_five);
                                                        pstmt_five.setString(1, b_id.getText());
                                                        pstmt_five.executeUpdate();

                                                        JOptionPane.showMessageDialog(this, "Successfuly Issured !! ");
                                                         b_id.setText("");
                                                         s_id.setText("");
                                                    }catch(Exception e){
                                                        JOptionPane.showMessageDialog(this, e);
                                                    }
                                                }
                                            }catch(Exception e){
                                                JOptionPane.showMessageDialog(this, e );
                                            }
                                        }else{
                                            JOptionPane.showMessageDialog(this, "Cannot Issure This Book");
                                        }
                                    }else{
                                        JOptionPane.showMessageDialog(this, "Cannot Identifier State");
                                    }
                                }catch(Exception e){
                                    JOptionPane.showMessageDialog(this, e);
                                }
                        }else{
                            JOptionPane.showMessageDialog(this, "Incorrect Student ID !!", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this, e);
                    }*/
                }else{
                    JOptionPane.showMessageDialog(this, "This Book is not Available","Error", JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        methode_logout();
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(true);
        jButton1.setOpaque(false);
        jButton1.setBackground(new Color(0,128,129));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issure_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issure_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issure_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issure_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issure_books().setVisible(true);
            }
        });
    }
    
    public Date check_date(String date) throws ParseException{
        SimpleDateFormat format = new SimpleDateFormat("yyyy-mm-dd");
        Date issuredate = (Date) format.parse(date);
        return  issuredate;
    }
    
  public void methode_logout(){
      
      try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
        PreparedStatement pstmt = conn.prepareStatement("delete from temporary_user");
        pstmt.executeUpdate();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lable_one;
    private javax.swing.JLabel lable_three;
    private javax.swing.JTextField s_id;
    // End of variables declaration//GEN-END:variables
}
