/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Sanadamal
 */
public class return_book extends javax.swing.JFrame {

    /**
     * Creates new form return_book
     */
    int x,y;
    public return_book() {
        initComponents();
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        b_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b_id = new javax.swing.JTextField();
        s_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lable_one = new javax.swing.JLabel();
        lable_three = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        jLabel8.setText("Log Out");

        jButton2.setText("Check Fine");

        jLabel6.setText("jLabel6");

        jLabel3.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 18)); // NOI18N
        jLabel3.setText("Book Name   :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Return Book");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 690, 43));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book ID         : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 136, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student ID      :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 204, -1, -1));

        b_id.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jPanel1.add(b_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 128, 204, 43));

        s_id.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jPanel1.add(s_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 189, 204, 45));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton1.setText("Return");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 291, 127, -1));

        lable_one.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        lable_one.setForeground(new java.awt.Color(255, 255, 255));
        lable_one.setText("Back");
        lable_one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lable_oneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lable_oneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lable_oneMouseExited(evt);
            }
        });
        jPanel1.add(lable_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 353, -1, -1));

        lable_three.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        lable_three.setForeground(new java.awt.Color(255, 255, 255));
        lable_three.setText("Cancel");
        lable_three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lable_threeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lable_threeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lable_threeMouseExited(evt);
            }
        });
        jPanel1.add(lable_three, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 353, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Get Student ID");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 201, 165, 33));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib_system/close.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib_system/minimize.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(599, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib_system/return_book_background.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 690, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lable_oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_oneMouseClicked
        // TODO add your handling code here:
        menu a = new menu();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_lable_oneMouseClicked

    private void lable_threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_threeMouseClicked
        // TODO add your handling code here:
        int result1 = JOptionPane.showConfirmDialog(this, "Are You Sure Want To Cancel Return That Book !!!!", "Question",JOptionPane.YES_NO_OPTION);
        if(result1 == JOptionPane.YES_OPTION){
            b_id.setText("");
            s_id.setText("");
            
        }
    }//GEN-LAST:event_lable_threeMouseClicked

    private void lable_oneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_oneMouseEntered
        // TODO add your handling code here:
        lable_one.setForeground(Color.red);
    }//GEN-LAST:event_lable_oneMouseEntered

    private void lable_oneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_oneMouseExited
        // TODO add your handling code here:
        lable_one.setForeground(Color.black);
    }//GEN-LAST:event_lable_oneMouseExited

    private void lable_threeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_threeMouseEntered
        // TODO add your handling code here:
        lable_three.setForeground(Color.red);
    }//GEN-LAST:event_lable_threeMouseEntered

    private void lable_threeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lable_threeMouseExited
        // TODO add your handling code here:
        lable_three.setForeground(Color.black);
    }//GEN-LAST:event_lable_threeMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        if(b_id.getText().equals("") || s_id.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Empty Feeld !!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                String sql ="select * from available_books where b_id=?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, b_id.getText());
                ResultSet rs =pstmt.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "This Book is Already Exist !!", "Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    try{
                        String sql_one ="select * from issure_books where b_id =? and s_id=?";
                        PreparedStatement pstmt_one = conn.prepareStatement(sql_one);
                        pstmt_one.setString(1, b_id.getText());
                        pstmt_one.setString(2, s_id.getText());
                        ResultSet rs_one = pstmt_one.executeQuery();
                        if(rs_one.next()){
                                java.util.Date date = new java.util.Date();
                                java.sql.Date sql_return_date = new java.sql.Date(date.getTime());
                                float daysBetween = 0 ;
                                Date issure = get_issure_date();

                                int result = get_duration();

                                try{
                                    String sql_two ="select * from all_books where b_id=?";
                                    PreparedStatement pstmt_two =conn.prepareStatement(sql_two);
                                    pstmt_two.setString(1, b_id.getText());
                                    ResultSet rs_two = pstmt_two.executeQuery();
                                    if(rs_two.next()){
                                        String book_category = rs_two.getString(2);
                                        String book_name = rs_two.getString(3);
                                        String authour_name = rs_two.getString(4);
                                        String book_issure = rs_two.getString(5);
                                        String book_floor = rs_two.getString(6);
                                        String book_rack = rs_two.getString(7);

                                        String sql_three ="insert into available_books values (?, ?, ?, ?, ?, ?, ?)";
                                        PreparedStatement pstmt_three = conn.prepareStatement(sql_three);
                                        pstmt_three.setString(1, b_id.getText());
                                        pstmt_three.setString(2, book_category);
                                        pstmt_three.setString(3, book_name);
                                        pstmt_three.setString(4, authour_name);
                                        pstmt_three.setString(5, book_issure);
                                        pstmt_three.setString(6, book_floor);
                                        pstmt_three.setString(7, book_rack);
                                        pstmt_three.executeUpdate();

                                        String sql_four ="delete from issure_books where b_id=?";
                                        PreparedStatement pstmt_four =conn.prepareStatement(sql_four);
                                        pstmt_four.setString(1, b_id.getText());
                                        pstmt_four.executeUpdate();
                                           try{
                                                  long difference = sql_return_date.getTime() - issure.getTime();
                                                  daysBetween = (difference/(1000*60*60*24));
                                                  JOptionPane.showMessageDialog(this, "Date Difference = "+daysBetween);
                                             }catch(Exception e){
                                                 JOptionPane.showMessageDialog(this, e);
                                            }

                                            if( daysBetween > (result + 14) ){
                                            float fine_value_one = get_fine_value(1);
                                            float fine_value_two = get_fine_value(2);
                                            float fine_value_three = get_fine_value(3);
                                            float value_one = ((7*fine_value_one)+(7*fine_value_two)+((daysBetween-14)*fine_value_three));
                                            JOptionPane.showMessageDialog(this, "Fine Value ="+value_one+"\nYour Fine Will Added");
                                            add_fine(value_one);
                                        }else if((daysBetween > (result+7)) && (result +14) >= daysBetween){
                                            float fine_value_one = get_fine_value(1);
                                            float fine_value_two = get_fine_value(2);
                                            float value_two =(7*fine_value_one)+((daysBetween-7)*fine_value_two);
                                            JOptionPane.showMessageDialog(this, "Fine Value ="+value_two+"\nYour Fine Will Added");
                                            add_fine(value_two);
                                        }else if((daysBetween > result) && ((result +7) >= daysBetween)){
                                            float fine_value_one = get_fine_value(1);
                                            float value_three =((daysBetween - result) * fine_value_one);
                                            JOptionPane.showMessageDialog(this, "Fine Value ="+value_three+"\nYour Fine Will Added");
                                            add_fine(value_three);
                                        }else{
                                            JOptionPane.showMessageDialog(this, "Good !!\nNo Fine Value to Add");
                                        }

                                            JOptionPane.showMessageDialog(this, "Successfuly Returned !!");

                                    }else{
                                        JOptionPane.showMessageDialog(this, "Cannot Find Book Details !!", "Error",JOptionPane.ERROR_MESSAGE);
                                    }
                                }catch(Exception e){
                                    JOptionPane.showMessageDialog(this, e);
                                }
                        }else{
                            JOptionPane.showMessageDialog(this, "You Entered Book ID or Student ID is incorrect !!", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this, e);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            } 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
         if(b_id.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Book ID", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            String sql ="select * from issure_books where b_id=?";
            try{
                 Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                ResultSet rs ;
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, b_id.getText());
                rs = pstmt.executeQuery(); 
                if(rs.next()){
                    get_IDvalue();
                }else{
                    JOptionPane.showMessageDialog(this, "This Book is Not Issured", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        methode_logout();
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(true);
        jButton1.setOpaque(false);
        jButton1.setBackground(new Color(0,128,129));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new return_book().setVisible(true);
            }
        });
    }
    
    public void get_value(){
            
          
          String issure_date = null;
         
            String sql ="select * from issure_books where b_id=?";
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                ResultSet rs ;
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, b_id.getText());
                rs = pstmt.executeQuery(); 
                        if(rs.next()){
                            issure_date = rs.getString(3);
                        }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
     }
    
    public void get_IDvalue(){
        
            String issure_id = null;
         
            String sql ="select * from issure_books where b_id=?";
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                ResultSet rs ;
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, b_id.getText());
                rs = pstmt.executeQuery(); 
                        if(rs.next()){
                            issure_id = rs.getString(2);
                        }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
        s_id.setText(issure_id);
     }
    
    public Date get_issure_date(){
        Date issure_date= null;
        String sql="select * from issure_books where b_id=?";
        try{
            Class.forName("com.mysql.jdbc.Driver");
                            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                ResultSet rs ;
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, b_id.getText());
                rs = pstmt.executeQuery(); 
                        if(rs.next()){
                            issure_date = rs.getDate(3);
                        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        return issure_date;
    }
    
    public float get_fine_value(int number){
        float value = 0;
        String sql="select * from fine_values where fine_id=?";
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                ResultSet rs ;
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1,number);
                rs = pstmt.executeQuery(); 
                        if(rs.next()){
                            value = rs.getFloat(2);
                        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        return value;
    }
    
    
    public int get_duration(){
    int duration;
    String result="Two Week";
    String id = b_id.getText();
    try{
               Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                ResultSet rs ;
                String sql ="select duration from issure_books where b_id=?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1,id);
                rs = pstmt.executeQuery(); 
                        if(rs.next()){
                            result = rs.getString(1);
                        }else{
                            JOptionPane.showMessageDialog(this, "Cannot Find Duration");
                        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e);
    }
    
    if(result.equals("One Week")){
        duration =7;
    }else{
        duration = 14;
    }
    
    return duration;
    }
    
    public void add_fine(float fine){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
            String sql ="update fine_table set fine=? where s_index=?";
                      PreparedStatement pstmt_two = conn.prepareStatement(sql);
                      pstmt_two.setFloat(1, fine);
                      pstmt_two.setString(2, s_id.getText());
                      pstmt_two.executeUpdate();
                      JOptionPane.showMessageDialog(this, "Add Successfuly !");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    public void methode_logout(){
      
      try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
        PreparedStatement pstmt = conn.prepareStatement("delete from temporary_user");
        pstmt.executeUpdate();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
}
 
public int check(){
    int result = 0;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
        String chek="select * from available_books where b_id='"+b_id.getText()+"'";
        PreparedStatement pstmt = conn.prepareStatement(chek);
        ResultSet rs;
        rs=pstmt.executeQuery();
        if(rs.next()){
           //JOptionPane.showMessageDialog(this, "This book is already exsit","Error", JOptionPane.ERROR_MESSAGE);
            result= 1;
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
    }
    return result;
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b_id;
    private javax.swing.JTextField b_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lable_one;
    private javax.swing.JLabel lable_three;
    private javax.swing.JTextField s_id;
    // End of variables declaration//GEN-END:variables
}
