/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanadamal
 */
public class set_fine extends javax.swing.JFrame {

    /**
     * Creates new form set_fine
     */
    int x,y;
    public set_fine() {
        initComponents();
        current_fine_one();
        current_fine_two();
        current_fine_other();
        
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        two_week_one = new javax.swing.JTextField();
        other_one = new javax.swing.JTextField();
        one_week_one = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        one_week_two = new javax.swing.JTextField();
        two_week_two = new javax.swing.JTextField();
        other_two = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 49, 82));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cancel");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Set Fine");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, 881, 65));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("With in one Week ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 172, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("With in Two Weeks");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 229, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("After Three Week");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 284, -1, -1));

        two_week_one.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        two_week_one.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        two_week_one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                two_week_oneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                two_week_oneMouseExited(evt);
            }
        });
        jPanel1.add(two_week_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 222, 103, -1));

        other_one.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        other_one.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        other_one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                other_oneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                other_oneMouseExited(evt);
            }
        });
        jPanel1.add(other_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 277, 103, -1));

        one_week_one.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        one_week_one.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        one_week_one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                one_week_oneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                one_week_oneMouseExited(evt);
            }
        });
        jPanel1.add(one_week_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 165, 103, -1));

        jButton1.setBackground(new java.awt.Color(0, 128, 129));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton1.setText("Clear ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 165, -1, 40));

        jButton2.setBackground(new java.awt.Color(0, 128, 129));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 165, -1, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(".");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 174, 32, 27));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(".");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 236, 12, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(".");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 291, 24, -1));

        one_week_two.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        one_week_two.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        one_week_two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                one_week_twoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                one_week_twoMouseExited(evt);
            }
        });
        jPanel1.add(one_week_two, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 165, 84, -1));

        two_week_two.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        two_week_two.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        two_week_two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                two_week_twoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                two_week_twoMouseExited(evt);
            }
        });
        jPanel1.add(two_week_two, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 222, 84, -1));

        other_two.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        other_two.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        other_two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                other_twoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                other_twoMouseExited(evt);
            }
        });
        jPanel1.add(other_two, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 277, 84, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 179, 21, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 236, 21, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 291, 21, -1));

        jButton3.setBackground(new java.awt.Color(0, 128, 129));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton3.setText("Clear ");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 222, -1, 37));

        jButton4.setBackground(new java.awt.Color(0, 128, 129));
        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 222, -1, 37));

        jButton5.setBackground(new java.awt.Color(0, 128, 129));
        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton5.setText("Clear ");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 277, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 128, 129));
        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton6.setText("Reset");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 277, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Rupies");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cents");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 120, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib_system/close.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib_system/minimize.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 881, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanadamal\\Desktop\\lib_system\\set_fine_background.png")); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 880, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        menu m =new menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        one_week_one.setText("");
        one_week_two.setText("");     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String one =one_week_one.getText();
        String two = one_week_two.getText();
       
        boolean ckeck =check_integer_one(one, two);
        if(ckeck != true){
            
        }else{
            if(one.equals("") || two.equals("")){
                JOptionPane.showMessageDialog(this, "Empty Feeld !!");
            }else{
            int valueone = Integer.parseInt(one);
            int valuetwo = Integer.parseInt(two);
            float value;
            value =(float) (valueone+(valuetwo*0.01));
            try{
                 Class.forName("com.mysql.jdbc.Driver");
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                         String sql_two;
                        sql_two = "delete from one_week_fine";
                        PreparedStatement pstmt_two = conn.prepareStatement(sql_two);
                        pstmt_two.executeUpdate();
                        //JOptionPane.showMessageDialog(this, "Fine Dleated");
                        
                        String sql;
                        sql = "insert into fine_values values (?, ?)";
                        PreparedStatement pstmt = conn.prepareStatement(sql);
                        pstmt.setInt(1, 1);
                        pstmt.setFloat(2, value);
                        pstmt.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Successfuly Reset");
                        
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        two_week_one.setText("");
        two_week_two.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
        String one = two_week_one.getText();
        String two = two_week_two.getText();
        
        boolean check =  check_integer_two(one, two);
        if(check != true){
            
        }else{
            if(one.equals("") || two.equals("")){
                JOptionPane.showMessageDialog(this, "Empty Feeld !!");
            }else{
             int valueone = Integer.parseInt(one);
            int valuetwo = Integer.parseInt(two);
            float value;
            value =(float) (valueone+(valuetwo*0.01));
            try{
                 Class.forName("com.mysql.jdbc.Driver");
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                       String sql_two;
                        sql_two = "delete from two_week_fine";
                        PreparedStatement pstmt_two = conn.prepareStatement(sql_two);
                        pstmt_two.executeUpdate();
                        
                        String sql;
                        sql = "insert into fine_values values (?, ?)";
                        PreparedStatement pstmt = conn.prepareStatement(sql);
                        pstmt.setInt(1, 2);
                        pstmt.setFloat(2, value);
                        pstmt.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Successfuly Add");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        other_one.setText("");
        other_two.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String one = other_one.getText();
        String two = other_two.getText();
        
        boolean check = check_integer_other(one, two);
        if(check != true){
            
        }else{
            if(one.equals("") || two.equals("")){
                JOptionPane.showMessageDialog(this, "Empty Field !!", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                 int valueone = Integer.parseInt(one);
                 int valuetwo = Integer.parseInt(two);
                float value;
                value =(float) (valueone+(valuetwo*0.01));
                try{
                     Class.forName("com.mysql.jdbc.Driver");
                            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
                        String sql_two;
                        sql_two = "delete from other_fine";
                        PreparedStatement pstmt_two = conn.prepareStatement(sql_two);
                        pstmt_two.executeUpdate();
                            
                            String sql;
                            sql = "insert into fine_values values (?, ?)";
                            PreparedStatement pstmt = conn.prepareStatement(sql);
                            pstmt.setInt(1, 3);
                            pstmt.setFloat(2, value);
                            pstmt.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Successfuly Add");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void one_week_oneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_one_week_oneMouseEntered
        // TODO add your handling code here:
        one_week_one.setBackground(new Color(176,223,229));
    }//GEN-LAST:event_one_week_oneMouseEntered

    private void one_week_oneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_one_week_oneMouseExited
        // TODO add your handling code here:
        one_week_one.setBackground(Color.white);
    }//GEN-LAST:event_one_week_oneMouseExited

    private void one_week_twoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_one_week_twoMouseEntered
        // TODO add your handling code here:
        one_week_two.setBackground(new Color(176,223,229));
    }//GEN-LAST:event_one_week_twoMouseEntered

    private void one_week_twoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_one_week_twoMouseExited
        // TODO add your handling code here:
        one_week_two.setBackground(Color.white);
    }//GEN-LAST:event_one_week_twoMouseExited

    private void two_week_oneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_two_week_oneMouseEntered
        // TODO add your handling code here:
        two_week_one.setBackground(new Color(176,223,229));
    }//GEN-LAST:event_two_week_oneMouseEntered

    private void two_week_oneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_two_week_oneMouseExited
        // TODO add your handling code here:
        two_week_one.setBackground(Color.white);
    }//GEN-LAST:event_two_week_oneMouseExited

    private void two_week_twoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_two_week_twoMouseEntered
        // TODO add your handling code here:
        two_week_two.setBackground(new Color(176,223,229));
    }//GEN-LAST:event_two_week_twoMouseEntered

    private void two_week_twoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_two_week_twoMouseExited
        // TODO add your handling code here:
        two_week_two.setBackground(Color.white);
    }//GEN-LAST:event_two_week_twoMouseExited

    private void other_oneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_other_oneMouseEntered
        // TODO add your handling code here:
        other_one.setBackground(new Color(176,223,229));
    }//GEN-LAST:event_other_oneMouseEntered

    private void other_oneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_other_oneMouseExited
        // TODO add your handling code here:
        other_one.setBackground(Color.white);
    }//GEN-LAST:event_other_oneMouseExited

    private void other_twoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_other_twoMouseEntered
        // TODO add your handling code here:
        other_two.setBackground(new Color(176,223,229));
    }//GEN-LAST:event_other_twoMouseEntered

    private void other_twoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_other_twoMouseExited
        // TODO add your handling code here:
        other_two.setBackground(Color.white);
    }//GEN-LAST:event_other_twoMouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        methode_logout();
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(true);
        jButton1.setOpaque(false);
        jButton1.setBackground(new Color(0,128,129));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setContentAreaFilled(true);
        jButton2.setOpaque(false);
        jButton2.setBackground(new Color(0,128,129));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setContentAreaFilled(true);
        jButton3.setOpaque(false);
        jButton3.setBackground(new Color(0,128,129));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        jButton4.setContentAreaFilled(true);
        jButton4.setOpaque(false);
        jButton4.setBackground(new Color(0,128,129));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        jButton5.setContentAreaFilled(true);
        jButton5.setOpaque(false);
        jButton5.setBackground(new Color(0,128,129));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
        jButton5.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
        jButton6.setContentAreaFilled(true);
        jButton6.setOpaque(false);
        jButton6.setBackground(new Color(0,128,129));
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
        jButton6.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(set_fine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(set_fine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(set_fine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(set_fine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new set_fine().setVisible(true);
            }
        });
    }
    
    public boolean check_integer_one(String one_week, String two_week){
        try{
            Integer.parseInt(one_week);
            Integer.parseInt(two_week);
            return  true;
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please Enter Fine in Number Format", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
    
    public boolean check_integer_two(String one, String two){
        try{
            Integer.parseInt(one);
            Integer.parseInt(two);
            return  true;
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please Enter Fine in Number Format", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
    public boolean check_integer_other(String one, String two){
        try{
            Integer.parseInt(one);
            Integer.parseInt(two);
            return  true;
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please Enter Fine in Number Format", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
    
    public void current_fine_one(){
        String o_w_o = null;
        String o_w_t = null;
        float result = 0;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
            String sql_one ="select * from fine_values where fine_id=?";
            ResultSet rs;
            PreparedStatement pstmt = conn.prepareStatement(sql_one);
            pstmt.setInt(1, 1);
            rs = pstmt.executeQuery();
            if(rs.next()){
                  result = rs.getFloat(2);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        int zero = (int) (result*100);
        int one = (int) (zero/100);
        int two =(int) (zero%100);
        o_w_o = String.valueOf(one);
        o_w_t = String.valueOf(two);
        one_week_one.setText(o_w_o);
        one_week_two.setText(o_w_t);
       
    }
    
    public void current_fine_two(){
        String t_w_o = null;
        String t_w_t = null;
        float result = 0;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
            String sql_two ="select * from fine_values where fine_id=?";
            ResultSet rs;
            PreparedStatement pstmt = conn.prepareStatement(sql_two);
            pstmt.setInt(1, 2);
            rs = pstmt.executeQuery();
            if(rs.next()){
                result = rs.getFloat(2);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        int zero = (int) (result*100);
        int one = (int) (zero/100);
        int two =(int) (zero%100);
        t_w_o = String.valueOf(one);
        t_w_t = String.valueOf(two);
            two_week_one.setText(t_w_o);
            two_week_two.setText(t_w_t);
    }
    
    public void current_fine_other(){
        String o_o = null;
        String o_t = null;
        float result = 0;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
            String sql_two ="select * from fine_values where fine_id=?";
            ResultSet rs;
            PreparedStatement pstmt = conn.prepareStatement(sql_two);
            pstmt.setInt(1, 3);
            rs = pstmt.executeQuery();
            if(rs.next()){
                result = rs.getFloat(2);;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        int zero = (int) (result*100);
        int one = (int) (zero/100);
        int two =(int) (zero%100);
        o_o = String.valueOf(one);
        o_t = String.valueOf(two);
        other_one.setText(o_o);
        other_two.setText(o_t);
    }
    
public void methode_logout(){
      
      try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/lib_system?serverTimezone=UTC","root","");
        PreparedStatement pstmt = conn.prepareStatement("delete from temporary_user");
        pstmt.executeUpdate();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField one_week_one;
    private javax.swing.JTextField one_week_two;
    private javax.swing.JTextField other_one;
    private javax.swing.JTextField other_two;
    private javax.swing.JTextField two_week_one;
    private javax.swing.JTextField two_week_two;
    // End of variables declaration//GEN-END:variables
}
